apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversor
  namespace: production
spec:
#  replicas: 1 (hpa added below)
  selector:
    matchLabels:
      app: conversor

  template:
    metadata:
      labels:
        app: conversor
      annotations: # for service discovery
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        prometheus.io/path: "/metrics"

    spec:
      containers:
      - name: conversor
        image: thiagoduran/conversor-complete-devops:latest
        ports:
        - containerPort: 8000
        env:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: DATABASE_URL

        resources:
          requests:
            cpu: "300m"       # app had 386m peak
            memory: "250Mi"   # the app itself takes ~116Mi
          limits:
            cpu: "1000m"      # 1 core (~3x of peak), so that no pod takes it all
            memory: "350Mi"   # 3x 116Mi